import os
import requests
import streamlit as st

API_URL = os.getenv("API_URL", "http://127.0.0.1:8000")

st.set_page_config(
    page_title="UFC Predictor AI", page_icon=":boxing_glove:", layout="centered"
)

st.markdown(
    """
    <style>
    .main {
        background-color: #111111;
        color: #FFFFFF;
    }
    .stButton>button {
        width: 100%;
        background-color: #D20A0A; /* Rosso UFC */
        color: white;
        border-radius: 5px;
        border: none;
        font-weight: bold;
        padding: 10px;
        transition: 0.3s;
        margin-top: 15px; /* Spazio extra sopra il bottone */
    }
    .stButton>button:hover {
        background-color: #A00808;
        border: none;
        color: white;
    }
    .stTextInput>div>div>input {
        background-color: #222222;
        color: white;
        border: 1px solid #444444;
    }
    .stCheckbox > label {
        color: #FFFFFF !important;
        font-size: 14px;
    }
    .stCheckbox span[role="checkbox"][aria-checked="true"] {
        background-color: #D20A0A !important;
        border-color: #D20A0A !important;
    }
    h1.winner{
        color: #FFFFFF;
        font-size: 45px;
        margin-top: 10px;
    }
    .prediction-card {
        background-color: #222222;
        padding: 25px;
        border-radius: 10px;
        border-left: 8px solid #D20A0A;
        text-align: center;
        margin-top: 20px;
    }
    .confidence-text {
        color: #D20A0A;
        font-size: 24px;
        font-weight: bold;
    }
    .ai-act-disclaimer {
        font-size: 11px;
        color: #888888;
        text-align: center;
        margin-top: 50px;
        line-height: 1.4;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# Header
st.image("https://pngimg.com/d/ufc_PNG61.png", width=150)  # UFC Logo
st.title("AI BASED FIGHT PREDICTOR")

# Input Area
col1, col2 = st.columns(2)

with col1:
    f1_name = st.text_input("Fighter 1", placeholder="Es: Ilia Topuria")

with col2:
    f2_name = st.text_input("Fighter 2", placeholder="Es: Max Holloway")

is_five_rounds = st.checkbox("Title Fight / Main Event (5 Rounds)")

if st.button("PREDICT"):
    if f1_name and f2_name:
        with st.spinner("Analyzing fighters' statistics..."):
            try:
                # Payload aggiornato con il campo 'rounds'
                response = requests.post(
                    f"{API_URL}/predict",
                    json={
                        "f1_name": f1_name,
                        "f2_name": f2_name,
                        "rounds": 5 if is_five_rounds else 3,
                    },
                )

                if response.status_code == 200:
                    data = response.json()

                    st.markdown(
                        f"""
                        <div class="prediction-card">
                            <h3 style='margin-bottom: 0;'>PREDICTED WINNER</h3>
                            <h1 class='winner'>{data["prediction"].upper()}</h1>
                            <p style='margin-bottom: 5px;'>CONFIDENCE SCORE</p>
                            <span class="confidence-text">{data["confidence"]}</span>
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )
                else:
                    message = response.json().get("detail", "Unable to recover data")
                    st.error(f"Error: {message}")

            except Exception as e:
                st.error(f"Connection failed. Error: ({e})")
    else:
        st.warning("You must enter both fighters' names to continue.")

st.markdown(
    """
    <div class="ai-act-disclaimer">
        <b>Disclaimer:</b> Predictions are generated by an automated system based on an
        <b>Ensemble Model</b> that combines <b>LightGBM, LinearRegression, and SVC</b>
        algorithms. <br> The model analyzes historical data (fighter records, age,
        height) extracted in real time from the website
        <a href="http://ufcstats.com" target="_blank">ufcstats.com</a>.
        Predictions do not constitute financial or betting advice
        and are provided for informational purposes only.
    </div>
    """,
    unsafe_allow_html=True,
)
